// *****************************************************************************
// Copyright (C) 2025 EclipseSource and others.
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License v. 2.0 which is available at
// http://www.eclipse.org/legal/epl-2.0.
//
// SPDX-License-Identifier: EPL-2.0 OR GPL-2.0-only WITH Classpath-exception-2.0
// *****************************************************************************

/**
 * Stored application generated by Mini Atoms.
 */
export interface StoredApp {
    id: string;
    description: string;
    html: string;
    createdAt: string;
}

/**
 * User intent input for generation (natural language or template).
 */
export interface IntentInput {
    type: 'natural' | 'template';
    text?: string;
    templateId?: string;
}

export const MINI_ATOMS_STORAGE_KEY_CURRENT = 'mini_atoms_current';
export const MINI_ATOMS_STORAGE_KEY_APPS = 'mini_atoms_apps';

export const MINI_ATOMS_DESCRIPTION_MAX_LENGTH = 2000;
